[package]
name = "webrtc-unreliable"
version = "0.5.2"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"
description = "UDP-like (unreliable, unordered) communication between Javascript/WebAssembly and native Rust via WebRTC"
repository = "https://github.com/kyren/webrtc-unreliable"
documentation = "https://docs.rs/webrtc-unreliable"
readme = "README.md"
keywords = ["wasm", "webrtc"]
license = "MIT"

[dependencies]
async-io = "1.6"
byteorder = "1.4.3"
crc = "3.0.0"
futures-channel = { version = "0.3.21", features = ["sink"] }
futures-core = { version = "0.3.21" }
futures-util = { version = "0.3.21", features = ["sink"] }
futures = "0.3.21"
openssl = "0.10.38"
rand = "0.8.5"

[dev-dependencies]
clap = "3.0"
env_logger = "0.9"
futures = { version = "0.3" }
tokio = { version = "1.0", features = ["macros", "net", "rt-multi-thread"] }
